(() => {
  'use strict';
  const G=window.GraphSCIICore;
  if(!G)throw Error('GraphSCII core missing');
  const {C,R,W,H,MAP,node,pos,nearestNode,normalize,compile,line,bezier,ellipse,validate}=G;
  const gc=document.querySelector('#glyph-canvas'),oc=document.querySelector('#overlay-canvas'),g=gc.getContext('2d'),o=oc.getContext('2d');
  const status=document.querySelector('#status'),overlap=document.querySelector('#overlap-status'),undo=document.querySelector('#undo'),clear=document.querySelector('#clear'),show=document.querySelector('#show-nodes'),buttons=[...document.querySelectorAll('[data-tool]')];
  gc.width=oc.width=C*W;gc.height=oc.height=R*H;
  let tool='freehand',paths=[],preview=[],hover=null,gesture=null,bez=[];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function setStatus(s){status.textContent=s}
  function canvasPoint(e){const r=oc.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*oc.width,0,oc.width),y:clamp((e.clientY-r.top)/r.height*oc.height,0,oc.height)}}
  function pushRaw(a,p){const q=a.at(-1);if(!q||Math.hypot(p.x-q.x,p.y-q.y)>=.15)a.push(p)}
  function cp(s){return MAP[`${s.from}>${s.to}`]??null}
  function cellMap(all){const m=new Map();for(const p of all){validate(p.segments);for(const s of p.segments){const code=cp(s);if(code==null)throw Error(`missing ${s.from}>${s.to}`);const k=`${s.cellX},${s.cellY}`,v=m.get(k)||{x:s.cellX,y:s.cellY,c:[]};v.c.push(code);m.set(k,v)}}return m}
  function bg(){const c=getComputedStyle(gc).backgroundColor;return c&&c!=='rgba(0, 0, 0, 0)'?c:'#fff'}
  function drawNodes(){if(!show.checked)return;o.fillStyle='rgba(80,100,120,.35)';for(let x=0;x<=C;x++)for(let y=0;y<R;y++)for(let i=0;i<16;i++){const p=pos(node('V',x,y,i));o.fillRect(p.x-1,p.y-1,2,2)}for(let y=0;y<=R;y++)for(let x=0;x<C;x++)for(let i=0;i<8;i++){const p=pos(node('H',y,x,i));o.fillRect(p.x-1,p.y-1,2,2)}}
  function drawBez(){if(!bez.length)return;o.strokeStyle='rgba(220,70,45,.55)';o.lineWidth=1.5;o.setLineDash([5,4]);o.beginPath();bez.forEach((n,i)=>{const p=pos(n);i?o.lineTo(p.x,p.y):o.moveTo(p.x,p.y)});o.stroke();o.setLineDash([])}
  function render(){g.clearRect(0,0,gc.width,gc.height);g.fillStyle=bg();g.fillRect(0,0,gc.width,gc.height);g.strokeStyle='rgba(127,127,127,.16)';g.lineWidth=1;g.beginPath();for(let x=0;x<=C;x++){g.moveTo(x*W+.5,0);g.lineTo(x*W+.5,R*H)}for(let y=0;y<=R;y++){g.moveTo(0,y*H+.5);g.lineTo(C*W,y*H+.5)}g.stroke();const all=[...paths];if(preview.length)all.push({segments:preview});const m=cellMap(all);g.font=`${H}px GraphSCII`;g.textBaseline='top';g.textAlign='left';g.fillStyle='#111';let bad=0;for(const v of m.values()){const u=[...new Set(v.c)];if(u.length>1)bad++;g.fillText(String.fromCodePoint(u[0]),v.x*W,v.y*H)}o.clearRect(0,0,oc.width,oc.height);drawNodes();o.strokeStyle='rgba(210,50,35,.85)';o.lineWidth=1.5;for(const v of m.values())if(new Set(v.c).size>1)o.strokeRect(v.x*W+2,v.y*H+2,W-4,H-4);if(hover){const p=pos(hover);o.fillStyle='#d43b2f';o.beginPath();o.arc(p.x,p.y,3.5,0,Math.PI*2);o.fill()}drawBez();overlap.textContent=bad?`${bad} overlap cell${bad===1?'':'s'} awaiting connector composition`:'Exact node semantics only';undo.disabled=clear.disabled=!paths.length}
  function commit(t,segs,closed=false){if(!segs.length)return false;try{validate(segs)}catch(e){console.error('Refusing broken path',e);return false}paths.push({tool:t,closed,segments:segs.map(s=>({...s}))});preview=[];render();return true}
  function instruction(t){if(t==='freehand')return'Freehand: mouse input is normalized, then compiled through exact shared boundary nodes.';if(t==='line')return'Line: drag from one GraphSCII node to another.';if(t==='bezier')return'Bezier: click four GraphSCII nodes — start, control 1, control 2, end.';return'Ellipse: drag between two GraphSCII nodes.'}
  function choose(t){tool=t;gesture=null;preview=[];bez=[];buttons.forEach(b=>{const a=b.dataset.tool===t;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});setStatus(instruction(t));render()}
  buttons.forEach(b=>b.addEventListener('click',()=>choose(b.dataset.tool)));
  oc.addEventListener('pointerdown',e=>{e.preventDefault();oc.focus();const p=canvasPoint(e),n=nearestNode(p.x,p.y);hover=n;if(tool==='bezier'){bez.push(n);if(bez.length===4){const s=bezier(bez);setStatus(commit('bezier',s)?`Bezier committed: ${s.length} continuous exact segments.`:'Bezier rejected rather than committing a broken path.');bez=[]}else setStatus(`Bezier point ${bez.length}/4 selected.`);render();return}oc.setPointerCapture(e.pointerId);gesture=tool==='freehand'?{id:e.pointerId,start:n,raw:[pos(n)]}:{id:e.pointerId,start:n};preview=[];render()});
  oc.addEventListener('pointermove',e=>{const p=canvasPoint(e);hover=nearestNode(p.x,p.y);if(!gesture||gesture.id!==e.pointerId){render();return}if(tool==='freehand'){const evs=typeof e.getCoalescedEvents==='function'?e.getCoalescedEvents():[e];for(const q of evs)pushRaw(gesture.raw,canvasPoint(q));pushRaw(gesture.raw,p);preview=compile(normalize(gesture.raw,gesture.start),gesture.start,null,true)}else if(tool==='line')preview=line(gesture.start,hover);else if(tool==='ellipse')preview=ellipse(gesture.start,hover);render()});
  function finish(e){if(!gesture||gesture.id!==e.pointerId)return;let s=preview;if(tool==='freehand'){pushRaw(gesture.raw,canvasPoint(e));s=compile(normalize(gesture.raw,gesture.start),gesture.start,null,true)}const ok=commit(tool,s,tool==='ellipse');setStatus(ok?`${tool} committed: ${s.length} continuous exact segments.`:`${tool} rejected rather than committing a broken path.`);preview=[];gesture=null;render()}
  oc.addEventListener('pointerup',finish);oc.addEventListener('pointercancel',e=>{if(gesture?.id!==e.pointerId)return;gesture=null;preview=[];setStatus(`${instruction(tool)} Gesture cancelled.`);render()});oc.addEventListener('pointerleave',()=>{if(!gesture){hover=null;render()}});undo.addEventListener('click',()=>{paths.pop();setStatus('Undid last node path.');render()});clear.addEventListener('click',()=>{paths=[];preview=[];bez=[];gesture=null;setStatus('Canvas cleared.');render()});show.addEventListener('change',render);oc.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(paths.length){paths.pop();setStatus('Undid last node path.');render()}}if(e.key==='Escape'){gesture=null;preview=[];bez=[];setStatus(`${instruction(tool)} Current gesture cancelled.`);render()}});
  async function boot(){try{G.selfTest();await document.fonts.load(`${H}px GraphSCII`);choose(tool)}catch(e){console.error(e);setStatus(`GraphSCII Draw failed its topology check: ${e.message}`)}}
  boot();
})();
