(() => {
  'use strict';
  const C=24,R=12,W=24,H=48,PC={L:16,R:16,T:8,B:8},EDGES=['L','R','T','B'];
  const EPS=1e-6,NUDGE=.001,RESAMPLE=1.5,DEADBAND=.55;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const sameCell=(a,b)=>!!a&&!!b&&a.x===b.x&&a.y===b.y;
  const portCount=e=>e==='L'||e==='R'?16:8;
  function portPixel(e,i){if(e==='L')return[0,i];if(e==='R')return[7,i];if(e==='T')return[i,0];return[i,15]}
  function bitmapKey(a,ai,b,bi){let[x0,y0]=portPixel(a,ai);const[x1,y1]=portPixel(b,bi),rows=new Uint8Array(16),dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1;let er=dx+dy;for(;;){rows[y0]|=1<<x0;if(x0===x1&&y0===y1)break;const e2=er*2;if(e2>=dy){er+=dy;x0+=sx}if(e2<=dx){er+=dx;y0+=sy}}return[...rows].map(v=>v.toString(16).padStart(2,'0')).join('')}
  function buildLookup(){const fam=[['L','R'],['T','B'],['L','T'],['L','B'],['R','T'],['R','B']],owners=new Map(),m=Object.create(null);let n=0;for(const[a,b]of fam)for(let i=0;i<portCount(a);i++)for(let j=0;j<portCount(b);j++){const k=bitmapKey(a,i,b,j);let id=owners.get(k);if(id===undefined){id=n++;owners.set(k,id)}const cp=0xE000+id;m[`${a}${i}>${b}${j}`]=cp;m[`${b}${j}>${a}${i}`]=cp}if(Object.keys(m).length!==1664||n!==746)throw Error('straight lookup invariant');return m}
  const MAP=buildLookup();
  function node(axis,boundary,band,index){return{axis,boundary,band,index,key:`${axis}:${boundary}:${band}:${index}`}}
  function pos(n){return n.axis==='V'?{x:n.boundary*W,y:n.band*H+((n.index+.5)/16)*H}:{x:n.band*W+((n.index+.5)/8)*W,y:n.boundary*H}}
  function portToNode(x,y,p){const e=p[0],i=Number(p.slice(1));if(e==='L')return node('V',x,y,i);if(e==='R')return node('V',x+1,y,i);if(e==='T')return node('H',y,x,i);return node('H',y+1,x,i)}
  function nearestNode(x,y){const vx=clamp(Math.round(x/W),0,C),vy=clamp(Math.floor(y/H),0,R-1),vi=clamp(Math.round(((y-vy*H)/H)*16-.5),0,15),hy=clamp(Math.round(y/H),0,R),hx=clamp(Math.floor(x/W),0,C-1),hi=clamp(Math.round(((x-hx*W)/W)*8-.5),0,7),a=[node('V',vx,vy,vi),node('H',hy,hx,hi)];let best=a[0],bd=Infinity;for(const n of a){const p=pos(n),d=Math.hypot(p.x-x,p.y-y);if(d<bd){best=n;bd=d}}return best}
  function inCell(c,p,m=EPS){return p.x>=c.x*W-m&&p.x<=(c.x+1)*W+m&&p.y>=c.y*H-m&&p.y<=(c.y+1)*H+m}
  const inBounds=c=>c.x>=0&&c.x<C&&c.y>=0&&c.y<R;
  function adjacent(n){const a=[];if(n.axis==='V'){if(n.boundary>0)a.push({x:n.boundary-1,y:n.band});if(n.boundary<C)a.push({x:n.boundary,y:n.band})}else{if(n.boundary>0)a.push({x:n.band,y:n.boundary-1});if(n.boundary<R)a.push({x:n.band,y:n.boundary})}return a}
  function portInCell(n,c){if(n.axis==='V'&&n.band===c.y){if(n.boundary===c.x)return`L${n.index}`;if(n.boundary===c.x+1)return`R${n.index}`}if(n.axis==='H'&&n.band===c.x){if(n.boundary===c.y)return`T${n.index}`;if(n.boundary===c.y+1)return`B${n.index}`}return null}
  function initialCell(n,next){const o=pos(n),dx=next.x-o.x,dy=next.y-o.y,l=Math.hypot(dx,dy)||1,probe={x:o.x+dx/l*.25,y:o.y+dy/l*.25};const a=adjacent(n);for(const c of a)if(inCell(c,probe,0))return c;return a[0]||null}
  function opposite(e){if(e==='L')return'R';if(e==='R')return'L';if(e==='T')return'B';return'T'}
  function neighbor(c,e){if(e==='L')return{x:c.x-1,y:c.y};if(e==='R')return{x:c.x+1,y:c.y};if(e==='T')return{x:c.x,y:c.y-1};return{x:c.x,y:c.y+1}}
  function quantPort(c,e,p){if(e==='L'||e==='R')return`${e}${clamp(Math.round(((p.y-c.y*H)/H)*16-.5),0,15)}`;return`${e}${clamp(Math.round(((p.x-c.x*W)/W)*8-.5),0,7)}`}
  function firstExit(c,a,b){const dx=b.x-a.x,dy=b.y-a.y,L=c.x*W,RR=(c.x+1)*W,T=c.y*H,B=(c.y+1)*H,h=[];if(dx<-EPS)h.push({edge:'L',t:(L-a.x)/dx});if(dx>EPS)h.push({edge:'R',t:(RR-a.x)/dx});if(dy<-EPS)h.push({edge:'T',t:(T-a.y)/dy});if(dy>EPS)h.push({edge:'B',t:(B-a.y)/dy});let best=null;for(const q of h){if(q.t<-EPS||q.t>1+EPS)continue;const p={x:a.x+dx*q.t,y:a.y+dy*q.t};if(p.x<L-.001||p.x>RR+.001||p.y<T-.001||p.y>B+.001)continue;if(!best||q.t<best.t-EPS)best={edge:q.edge,t:Math.max(0,q.t),point:p};else if(Math.abs(q.t-best.t)<=EPS){const preferV=Math.abs(dx)>=Math.abs(dy),candV=q.edge==='L'||q.edge==='R',bestV=best.edge==='L'||best.edge==='R';if(candV===preferV&&bestV!==preferV)best={edge:q.edge,t:Math.max(0,q.t),point:p}}}return best}
  function resample(points,spacing=RESAMPLE){if(points.length<2)return points.map(p=>({...p}));const out=[{...points[0]}];let carry=0,prev={...points[0]};for(let i=1;i<points.length;i++){const t=points[i];let dx=t.x-prev.x,dy=t.y-prev.y,l=Math.hypot(dx,dy);if(l<EPS)continue;while(carry+l>=spacing){const need=spacing-carry,u=need/l;prev={x:prev.x+dx*u,y:prev.y+dy*u};out.push({...prev});dx=t.x-prev.x;dy=t.y-prev.y;l=Math.hypot(dx,dy);carry=0;if(l<EPS)break}carry+=l;prev={...t}}const last=points.at(-1),tail=out.at(-1);if(Math.hypot(last.x-tail.x,last.y-tail.y)>.1)out.push({...last});return out}
  function smooth(points){if(points.length<5)return points.map(p=>({...p}));const out=[{...points[0]}];for(let i=1;i<points.length-1;i++){const a=points[i-1],b=points[i],c=points[i+1];out.push({x:a.x*.2+b.x*.6+c.x*.2,y:a.y*.2+b.y*.6+c.y*.2})}out.push({...points.at(-1)});return out}
  function deadband(points){if(points.length<2)return points;const out=[points[0]];for(let i=1;i<points.length;i++){const p=points[i],q=out.at(-1);if(i===points.length-1||Math.hypot(p.x-q.x,p.y-q.y)>=DEADBAND)out.push(p)}return out}
  function normalize(raw,start){const s=pos(start),pts=[{...s},...raw.slice(1)];return deadband(smooth(resample(pts)))}

  function crossingWalk(points,start){if(!start||points.length<2)return null;let anchor=initialCell(start,points[1]);if(!anchor||!inBounds(anchor))return null;let cell={...anchor},cur=pos(start);const stack=[];for(let i=1;i<points.length;i++){const target=points[i];let guard=0;while(!inCell(cell,target,-.0001)){if(++guard>C+R+16)throw Error('crossing guard');const x=firstExit(cell,cur,target);if(!x)break;const next=neighbor(cell,x.edge);if(!inBounds(next))return{anchor,cell,crossings:stack,endPoint:x.point};const top=stack.at(-1),rev=top&&sameCell(top.fromCell,next)&&sameCell(top.toCell,cell),sp=!top?portInCell(start,cell):null,bounce=!top&&sp&&x.edge===sp[0]&&!!portInCell(start,next);if(rev)stack.pop();else if(bounce)anchor={...next};else stack.push({fromCell:{...cell},toCell:{...next},edge:x.edge,point:{...x.point}});cell=next;const rx=target.x-x.point.x,ry=target.y-x.point.y,l=Math.hypot(rx,ry);cur=l>EPS?{x:x.point.x+rx/l*NUDGE,y:x.point.y+ry/l*NUDGE}:{...x.point}}cur={...target}}return{anchor,cell,crossings:stack,endPoint:points.at(-1)}}
  function segment(c,a,b){const from=portInCell(a,c),to=portInCell(b,c);if(!from||!to||from===to)return null;if(from[0]===to[0])throw Error(`same-edge ${from}>${to}`);if(MAP[`${from}>${to}`]==null)throw Error(`missing ${from}>${to}`);return{cellX:c.x,cellY:c.y,from,to}}
  function nearestTail(c,entry,p){const ep=portInCell(entry,c);if(!ep)return entry;let best=entry,bp=pos(entry),bd=Math.hypot(bp.x-p.x,bp.y-p.y);for(const e of EDGES){if(e===ep[0])continue;for(let i=0;i<PC[e];i++){const n=portToNode(c.x,c.y,`${e}${i}`),q=pos(n),d=Math.hypot(q.x-p.x,q.y-p.y);if(d<bd){best=n;bd=d}}}return best}
  function validate(segs,start=null,end=null){let prev=start;for(const s of segs){if(s.from[0]===s.to[0])throw Error('same-edge survived');if(MAP[`${s.from}>${s.to}`]==null)throw Error('unknown semantic');const a=portToNode(s.cellX,s.cellY,s.from),b=portToNode(s.cellX,s.cellY,s.to);if(prev&&a.key!==prev.key)throw Error(`broken continuity ${prev.key} != ${a.key}`);prev=b}if(end&&prev&&prev.key!==end.key)throw Error(`wrong end ${prev.key} != ${end.key}`);return true}
  function segmentsFromWalk(w,start,end=null,closeTail=true){if(!w)return[];const segs=[];let cell={...w.anchor},cur=start;for(const x of w.crossings){if(!sameCell(x.fromCell,cell))throw Error('crossing stack discontinuity');const p=quantPort(x.fromCell,x.edge,x.point),n=portToNode(x.fromCell.x,x.fromCell.y,p),s=segment(cell,cur,n);if(!s)throw Error('empty crossing segment');segs.push(s);cur=n;cell={...x.toCell}}if(end){if(cur.key!==end.key){const s=segment(cell,cur,end);if(!s)throw Error('unreachable explicit endpoint');segs.push(s);cur=end}}else if(closeTail){const n=nearestTail(cell,cur,w.endPoint);if(n.key!==cur.key){const s=segment(cell,cur,n);if(s){segs.push(s);cur=n}}}validate(segs,start,end);return segs}
  function compile(points,start,end=null,closeTail=true){if(!start||points.length<2)return[];try{return segmentsFromWalk(crossingWalk(points,start),start,end,closeTail)}catch(e){console.error('GraphSCII path rejected:',e);return[]}}
  function line(a,b){return!a||!b||a.key===b.key?[]:compile([pos(a),pos(b)],a,b,false)}
  function cubic(a,b,c,d,t){const q=1-t;return{x:q*q*q*a.x+3*q*q*t*b.x+3*q*t*t*c.x+t*t*t*d.x,y:q*q*q*a.y+3*q*q*t*b.y+3*q*t*t*c.y+t*t*t*d.y}}
  function bezier(ns){const p=ns.map(pos),pts=[p[0]];for(let i=1;i<=160;i++)pts.push(cubic(p[0],p[1],p[2],p[3],i/160));return compile(pts,ns[0],ns[3],false)}
  function ellipse(a,b){a=pos(a);b=pos(b);const cx=(a.x+b.x)/2,cy=(a.y+b.y)/2,rx=Math.abs(b.x-a.x)/2,ry=Math.abs(b.y-a.y)/2;if(rx<W*.75||ry<H*.75)return[];const start=nearestNode(cx+rx,cy),sp=pos(start),pts=[sp],steps=clamp(Math.ceil(2*Math.PI*Math.sqrt((rx*rx+ry*ry)/2)/1.5),128,512);for(let i=1;i<=steps;i++){const z=i/steps*Math.PI*2;pts.push({x:cx+Math.cos(z)*rx,y:cy+Math.sin(z)*ry})}pts.push(sp);return compile(pts,start,start,false)}
  function selfTest(){const s=node('V',5,5,8),p=pos(s),j=[p,{x:p.x+30,y:p.y+1},{x:p.x+18,y:p.y+1},{x:p.x+55,y:p.y+5}],a=compile(j,s,null,false);validate(a,s);const seen=new Set();for(const x of a){const k=`${x.cellX},${x.cellY}`;if(seen.has(k))throw Error('jitter revisit');seen.add(k)}const e=node('V',10,5,9),b=line(s,e);validate(b,s,e);return true}
  window.GraphSCIICore={C,R,W,H,PC,MAP,node,pos,portToNode,nearestNode,normalize,compile,line,bezier,ellipse,validate,selfTest};
})();
